# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pi_gw_panel.routing_api.proto import router_command_pb2 as router__command__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in router_command_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoutingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TestRoute = channel.unary_unary(
                '/xray.app.router.command.RoutingService/TestRoute',
                request_serializer=router__command__pb2.TestRouteRequest.SerializeToString,
                response_deserializer=router__command__pb2.RoutingContext.FromString,
                _registered_method=True)


class RoutingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def TestRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoutingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TestRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.TestRoute,
                    request_deserializer=router__command__pb2.TestRouteRequest.FromString,
                    response_serializer=router__command__pb2.RoutingContext.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xray.app.router.command.RoutingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xray.app.router.command.RoutingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoutingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TestRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xray.app.router.command.RoutingService/TestRoute',
            router__command__pb2.TestRouteRequest.SerializeToString,
            router__command__pb2.RoutingContext.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
